runtime: python310

instance_class: F1

env_variables:
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: '1029'
  POSTGRES_DB: 'advice_health'
  POSTGRES_HOST: localhost

handlers:
  - url: /img
    static_dir: static/img

  - url: /script
    static_dir: static/script

  - url: /styles
    static_dir: static/styles
